version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: app-template-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-production-secret-key-min-32-chars-change-me-please}
        BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
        DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/appdb}
    container_name: app-template-app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/appdb
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-production-secret-key-min-32-chars-change-me-please}
      BETTER_AUTH_URL: http://localhost:3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
